import {
    FaCheck,
    FaEye,
    FaEdit,
    FaTrash,
    FaEyeSlash,
    FaPowerOff,
    FaAngleLeft,
    FaAngleUp,
    FaAngleDown,
    FaAngleRight,
    FaDashcube,
    FaList,
    FaUsers,
    FaUserFriends,
    FaLongArrowAltUp,
    FaLongArrowAltDown,
    FaLongArrowAltLeft,
    FaAngleDoubleLeft,
    FaAngleDoubleRight,
    FaPlus,
    FaSearch,
    FaTimes,
    FaPlayCircle,
    FaPauseCircle,
    FaStopCircle,
    FaCalendar,
    FaRandom,
    FaLayerGroup,
    FaTimesCircle,
    FaEllipsisV 
  } from "react-icons/fa";
  import { FaGear } from "react-icons/fa6";
  import { MdLogin, MdLogout } from "react-icons/md";
  import { IoMdMenu, IoMdFemale, IoMdMale } from "react-icons/io";
  import { BsThreeDotsVertical, BsFillKanbanFill } from "react-icons/bs";
  import { SlCloudUpload } from "react-icons/sl";
  import {FiGrid} from "react-icons/fi"
  
  export {
    FaDashcube,
    FaCheck,
    FaPlus,
    FaEye,
    FaEdit,
    FaTrash,
    FaEyeSlash,
    FaPowerOff,
    FaAngleLeft,
    FaAngleUp,
    FaAngleDown,
    FaAngleRight,
    FaGear,
    FaList,
    FaUsers,
    FaUserFriends,
    IoMdMenu,
    IoMdFemale,
    IoMdMale,
    FaLongArrowAltUp,
    FaLongArrowAltDown,
    FaLongArrowAltLeft,
    FaAngleDoubleLeft,
    FaAngleDoubleRight,
    FaSearch,
    FaTimes,
    FaLayerGroup,
    FaPlayCircle,
    FaPauseCircle,
    FaTimesCircle,
    FaStopCircle,
    FaCalendar,
    FaRandom,
    BsThreeDotsVertical as ThDotV,
    BsFillKanbanFill as BsKanBan,
    MdLogin,
    MdLogout,
    SlCloudUpload,
    FaEllipsisV ,
    FiGrid
  };